apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: bolbol-mysql
spec:
  storageClassName: hiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi